version: '3.8'
services:
  db:
    image: postgres:16-alpine
    container_name: shortener_db
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=shortener_db
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      voidlink_net:
        aliases:
          - db

  api:
    build: ./backend
    container_name: fastapi_app
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app:/app/backend
      - DATABASE_URL=postgresql://admin:root@db:5432/shortener_db
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - voidlink_net

  frontend:
    build: ./frontend
    container_name: shortener_frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      - api
    networks:
      - voidlink_net

  bot:
    build:
      context: ./backend
      dockerfile: bot/Dockerfile
    container_name: voidlink_bot
    restart: always
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://admin:root@db:5432/shortener_db
      - PYTHONPATH=/app
    working_dir: /app
    command: python bot/bot.py
    depends_on:
      - db
    networks:
      - voidlink_net # ОБОВ'ЯЗКОВО, щоб бачити базу

networks:
  voidlink_net:
    name: voidlink_network

